theme: jekyll-theme-cayman
title: Vietnam Address Converter
description: Thư viện JavaScript/TypeScript để tự động chuyển đổi địa chỉ hành chính Việt Nam từ cũ sang mới theo Nghị quyết 202/2025/QH15

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

url: "https://quangtam.github.io"
baseurl: "/vietnam-address-converter"

github:
  repository_url: "https://github.com/quangtam/vietnam-address-converter"
  
exclude:
  - node_modules/
  - npm-debug.log*
  - package*.json
  - rollup.config.js
  - tsconfig*.json
  - src/
  - examples/
  - .github/
  - test-library.mjs
